package tests;

import static org.junit.Assert.fail;

import java.io.IOException;

import javax.script.Invocable;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

import wyc.WycMain;
import wyjc.WyjcMain;
import wyjc.util.WyjcBuildTask;
import main.Whiley2Javascript;

public final class TestUtils {
	
	/**
	 * The location of the whiley test cases
	 */
	public static final String WHILEY_TEST_DIR = "tests\\"; //"../../wdk/tests/";
	
	//File extensions
	private static final String WHILEY_EXT = ".whiley";
	private static final String WYIL_EXT = ".wyil";
	
	//Where to store wyil files generated by the whiley compiler for test cases 
	private static final String TEST_WYIL_DIR = "tests\\";
	
	/**
	 * Run a whiley test
	 * @param name
	 * @throws IOException
	 */
	public static void runValidTest(String name) {
		String js = generateJavascript(name);
		
		//Execute JS
		try {
			execute(js);
		} catch (ScriptException e) {
			fail(e.getMessage());
		}
	}
	
	public static void execute(String javascript) throws ScriptException{
		try {
			execute(javascript, "test");
		} catch (NoSuchMethodException e){
			throw new RuntimeException("No test method found in javascript");
		}
	}
	
	public static Object execute(String javascript, String function, Object... params) throws ScriptException, NoSuchMethodException{
		ScriptEngine nashorn = new ScriptEngineManager().getEngineByName("nashorn");
		nashorn.eval(javascript);
		
		Invocable engine = (Invocable) nashorn;
		
		Object result = engine.invokeFunction(function, params);
		return result;
	}
	
	private static String generateJavascript(String name){
		String wyFile = WHILEY_TEST_DIR + name + WHILEY_EXT;
		String wyilFile = TEST_WYIL_DIR + name + WYIL_EXT;
		
		//Compile the file
		String[] args = {
				"-wd", WHILEY_TEST_DIR, //Whiley src location 
				"-wyildir", TEST_WYIL_DIR, //Wyil compilation dir
				//"-wp", "lib/wyrt-v0.3.39.jar",
				wyFile};
		int r = new WyjcMain(new WyjcBuildTask(), WyjcMain.DEFAULT_OPTIONS).run(args);
		
		//Check compilation results
		if (r != WycMain.SUCCESS){
			fail("Test failed to compile");
		}
		
		//Generate JS
		String js = Whiley2Javascript.convert(wyilFile);
		System.out.println(js);
		
		return js;
	}
}
